# Generated by Django 4.2.3 on 2023-07-25 03:40

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Account',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Plan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('package', models.CharField(choices=[('novice', 'Novice'), ('elite', 'Elite')], default=None, max_length=10, verbose_name='plan')),
                ('level', models.PositiveIntegerField(default=1)),
                ('link', models.URLField(editable=False, null=True, unique=True, verbose_name='link')),
                ('commission', models.DecimalField(decimal_places=2, default=0.0, editable=False, max_digits=10)),
                ('is_paid', models.BooleanField(blank=True, default=True, verbose_name='account validity')),
                ('referals', models.ManyToManyField(related_name='invites', to='query.account')),
            ],
        ),
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('slug', models.SlugField()),
                ('content', models.TextField()),
                ('created_at', models.DateTimeField(auto_now=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='query.account')),
            ],
        ),
        migrations.AddField(
            model_name='account',
            name='plan',
            field=models.ManyToManyField(related_name='subscription', to='query.plan'),
        ),
        migrations.AddField(
            model_name='account',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='account', to=settings.AUTH_USER_MODEL),
        ),
    ]
