# Generated by Django 4.2.3 on 2023-07-25 04:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('query', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='plan',
            field=models.ManyToManyField(blank=True, related_name='subscription', to='query.plan'),
        ),
    ]
